[并行查询的参数调优]章节，去掉两个查询不到的参数
oceanbase/oceanbase-doc pull request #153
Opened 2022-05-04 02:35 UTC by ChrisYuan

[并行查询的参数调优]章节，去掉两个查询不到的参数

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2404284/166616238-5a0b586e-3beb-4a43-9d81-93c689c7b564.png">

2022-05-04 02:36 UTC, ChrisYuan commented
<img width="375" alt="image" src="https://user-images.githubusercontent.com/2404284/166616295-af5184bb-b04b-42f6-8aab-5d32716ec07c.png">
只能查到parallel的四个参数。

2022-05-10 07:04 UTC, MeinaWang requested changes
这两个为隐藏变量，社区版是支持的。不能用show 语句查询，可以通过内部表 __all_sys_variable查询。
两个参数的内容保留，下边的文字改为“可以通过 SHOW VARIABLES 查看 parallel_servers_target 的值，通过 __all_sys_variable 查询 _force_parallel_query_dop 和 _force_parallel_dml_dop 的值。

2022-05-10 07:06 UTC, ChrisYuan commented
好的收到，我改一下重新提交一下pr，感谢老师答疑解惑

2022-05-10 11:55 UTC, ChrisYuan commented
搞定了，请求合并 @MeinaWang

2022-05-10 11:57 UTC, merged